// Code generated by go-swagger; DO NOT EDIT.

package operators

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"io"
	"net/http"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	"github.com/go-openapi/runtime/middleware"
	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/validate"

	"github.com/openshift/assisted-service/models"
)

// NewV2UpdateOperatorPropertiesParams creates a new V2UpdateOperatorPropertiesParams object
//
// There are no default values defined in the spec.
func NewV2UpdateOperatorPropertiesParams() V2UpdateOperatorPropertiesParams {

	return V2UpdateOperatorPropertiesParams{}
}

// V2UpdateOperatorPropertiesParams contains all the bound params for the v2 update operator properties operation
// typically these are obtained from a http.Request
//
// swagger:parameters V2UpdateOperatorProperties
type V2UpdateOperatorPropertiesParams struct {

	// HTTP Request Object
	HTTPRequest *http.Request `json:"-"`

	/*The operator name.
	  Required: true
	  In: path
	*/
	OperatorName string
	/*Operator properties to update.
	  Required: true
	  In: body
	*/
	OperatorProperties models.OperatorProperties
}

// BindRequest both binds and validates a request, it assumes that complex things implement a Validatable(strfmt.Registry) error interface
// for simple values it will use straight method calls.
//
// To ensure default values, the struct must have been initialized with NewV2UpdateOperatorPropertiesParams() beforehand.
func (o *V2UpdateOperatorPropertiesParams) BindRequest(r *http.Request, route *middleware.MatchedRoute) error {
	var res []error

	o.HTTPRequest = r

	rOperatorName, rhkOperatorName, _ := route.Params.GetOK("operator_name")
	if err := o.bindOperatorName(rOperatorName, rhkOperatorName, route.Formats); err != nil {
		res = append(res, err)
	}

	if runtime.HasBody(r) {
		defer r.Body.Close()
		var body models.OperatorProperties
		if err := route.Consumer.Consume(r.Body, &body); err != nil {
			if err == io.EOF {
				res = append(res, errors.Required("operatorProperties", "body", ""))
			} else {
				res = append(res, errors.NewParseError("operatorProperties", "body", "", err))
			}
		} else {
			// validate body object
			if err := body.Validate(route.Formats); err != nil {
				res = append(res, err)
			}

			ctx := validate.WithOperationRequest(r.Context())
			if err := body.ContextValidate(ctx, route.Formats); err != nil {
				res = append(res, err)
			}

			if len(res) == 0 {
				o.OperatorProperties = body
			}
		}
	} else {
		res = append(res, errors.Required("operatorProperties", "body", ""))
	}
	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

// bindOperatorName binds and validates parameter OperatorName from path.
func (o *V2UpdateOperatorPropertiesParams) bindOperatorName(rawData []string, hasKey bool, formats strfmt.Registry) error {
	var raw string
	if len(rawData) > 0 {
		raw = rawData[len(rawData)-1]
	}

	// Required: true
	// Parameter is provided by construction from the route
	o.OperatorName = raw

	return nil
}
