// Code generated by go-swagger; DO NOT EDIT.

package operators

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"net/http"

	"github.com/go-openapi/runtime"

	"github.com/openshift/assisted-service/models"
)

// V2UpdateOperatorPropertiesOKCode is the HTTP code returned for type V2UpdateOperatorPropertiesOK
const V2UpdateOperatorPropertiesOKCode int = 200

/*
V2UpdateOperatorPropertiesOK Success.

swagger:response v2UpdateOperatorPropertiesOK
*/
type V2UpdateOperatorPropertiesOK struct {
}

// NewV2UpdateOperatorPropertiesOK creates V2UpdateOperatorPropertiesOK with default headers values
func NewV2UpdateOperatorPropertiesOK() *V2UpdateOperatorPropertiesOK {

	return &V2UpdateOperatorPropertiesOK{}
}

// WriteResponse to the client
func (o *V2UpdateOperatorPropertiesOK) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.Header().Del(runtime.HeaderContentType) //Remove Content-Type on empty responses

	rw.WriteHeader(200)
}

// V2UpdateOperatorPropertiesBadRequestCode is the HTTP code returned for type V2UpdateOperatorPropertiesBadRequest
const V2UpdateOperatorPropertiesBadRequestCode int = 400

/*
V2UpdateOperatorPropertiesBadRequest Bad Request.

swagger:response v2UpdateOperatorPropertiesBadRequest
*/
type V2UpdateOperatorPropertiesBadRequest struct {

	/*
	  In: Body
	*/
	Payload *models.Error `json:"body,omitempty"`
}

// NewV2UpdateOperatorPropertiesBadRequest creates V2UpdateOperatorPropertiesBadRequest with default headers values
func NewV2UpdateOperatorPropertiesBadRequest() *V2UpdateOperatorPropertiesBadRequest {

	return &V2UpdateOperatorPropertiesBadRequest{}
}

// WithPayload adds the payload to the v2 update operator properties bad request response
func (o *V2UpdateOperatorPropertiesBadRequest) WithPayload(payload *models.Error) *V2UpdateOperatorPropertiesBadRequest {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the v2 update operator properties bad request response
func (o *V2UpdateOperatorPropertiesBadRequest) SetPayload(payload *models.Error) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *V2UpdateOperatorPropertiesBadRequest) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(400)
	if o.Payload != nil {
		payload := o.Payload
		if err := producer.Produce(rw, payload); err != nil {
			panic(err) // let the recovery middleware deal with this
		}
	}
}

// V2UpdateOperatorPropertiesUnauthorizedCode is the HTTP code returned for type V2UpdateOperatorPropertiesUnauthorized
const V2UpdateOperatorPropertiesUnauthorizedCode int = 401

/*
V2UpdateOperatorPropertiesUnauthorized Unauthorized.

swagger:response v2UpdateOperatorPropertiesUnauthorized
*/
type V2UpdateOperatorPropertiesUnauthorized struct {

	/*
	  In: Body
	*/
	Payload *models.InfraError `json:"body,omitempty"`
}

// NewV2UpdateOperatorPropertiesUnauthorized creates V2UpdateOperatorPropertiesUnauthorized with default headers values
func NewV2UpdateOperatorPropertiesUnauthorized() *V2UpdateOperatorPropertiesUnauthorized {

	return &V2UpdateOperatorPropertiesUnauthorized{}
}

// WithPayload adds the payload to the v2 update operator properties unauthorized response
func (o *V2UpdateOperatorPropertiesUnauthorized) WithPayload(payload *models.InfraError) *V2UpdateOperatorPropertiesUnauthorized {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the v2 update operator properties unauthorized response
func (o *V2UpdateOperatorPropertiesUnauthorized) SetPayload(payload *models.InfraError) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *V2UpdateOperatorPropertiesUnauthorized) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(401)
	if o.Payload != nil {
		payload := o.Payload
		if err := producer.Produce(rw, payload); err != nil {
			panic(err) // let the recovery middleware deal with this
		}
	}
}

// V2UpdateOperatorPropertiesForbiddenCode is the HTTP code returned for type V2UpdateOperatorPropertiesForbidden
const V2UpdateOperatorPropertiesForbiddenCode int = 403

/*
V2UpdateOperatorPropertiesForbidden Forbidden.

swagger:response v2UpdateOperatorPropertiesForbidden
*/
type V2UpdateOperatorPropertiesForbidden struct {

	/*
	  In: Body
	*/
	Payload *models.InfraError `json:"body,omitempty"`
}

// NewV2UpdateOperatorPropertiesForbidden creates V2UpdateOperatorPropertiesForbidden with default headers values
func NewV2UpdateOperatorPropertiesForbidden() *V2UpdateOperatorPropertiesForbidden {

	return &V2UpdateOperatorPropertiesForbidden{}
}

// WithPayload adds the payload to the v2 update operator properties forbidden response
func (o *V2UpdateOperatorPropertiesForbidden) WithPayload(payload *models.InfraError) *V2UpdateOperatorPropertiesForbidden {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the v2 update operator properties forbidden response
func (o *V2UpdateOperatorPropertiesForbidden) SetPayload(payload *models.InfraError) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *V2UpdateOperatorPropertiesForbidden) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(403)
	if o.Payload != nil {
		payload := o.Payload
		if err := producer.Produce(rw, payload); err != nil {
			panic(err) // let the recovery middleware deal with this
		}
	}
}

// V2UpdateOperatorPropertiesNotFoundCode is the HTTP code returned for type V2UpdateOperatorPropertiesNotFound
const V2UpdateOperatorPropertiesNotFoundCode int = 404

/*
V2UpdateOperatorPropertiesNotFound Error.

swagger:response v2UpdateOperatorPropertiesNotFound
*/
type V2UpdateOperatorPropertiesNotFound struct {

	/*
	  In: Body
	*/
	Payload *models.Error `json:"body,omitempty"`
}

// NewV2UpdateOperatorPropertiesNotFound creates V2UpdateOperatorPropertiesNotFound with default headers values
func NewV2UpdateOperatorPropertiesNotFound() *V2UpdateOperatorPropertiesNotFound {

	return &V2UpdateOperatorPropertiesNotFound{}
}

// WithPayload adds the payload to the v2 update operator properties not found response
func (o *V2UpdateOperatorPropertiesNotFound) WithPayload(payload *models.Error) *V2UpdateOperatorPropertiesNotFound {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the v2 update operator properties not found response
func (o *V2UpdateOperatorPropertiesNotFound) SetPayload(payload *models.Error) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *V2UpdateOperatorPropertiesNotFound) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(404)
	if o.Payload != nil {
		payload := o.Payload
		if err := producer.Produce(rw, payload); err != nil {
			panic(err) // let the recovery middleware deal with this
		}
	}
}

// V2UpdateOperatorPropertiesInternalServerErrorCode is the HTTP code returned for type V2UpdateOperatorPropertiesInternalServerError
const V2UpdateOperatorPropertiesInternalServerErrorCode int = 500

/*
V2UpdateOperatorPropertiesInternalServerError Error.

swagger:response v2UpdateOperatorPropertiesInternalServerError
*/
type V2UpdateOperatorPropertiesInternalServerError struct {

	/*
	  In: Body
	*/
	Payload *models.Error `json:"body,omitempty"`
}

// NewV2UpdateOperatorPropertiesInternalServerError creates V2UpdateOperatorPropertiesInternalServerError with default headers values
func NewV2UpdateOperatorPropertiesInternalServerError() *V2UpdateOperatorPropertiesInternalServerError {

	return &V2UpdateOperatorPropertiesInternalServerError{}
}

// WithPayload adds the payload to the v2 update operator properties internal server error response
func (o *V2UpdateOperatorPropertiesInternalServerError) WithPayload(payload *models.Error) *V2UpdateOperatorPropertiesInternalServerError {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the v2 update operator properties internal server error response
func (o *V2UpdateOperatorPropertiesInternalServerError) SetPayload(payload *models.Error) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *V2UpdateOperatorPropertiesInternalServerError) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(500)
	if o.Payload != nil {
		payload := o.Payload
		if err := producer.Produce(rw, payload); err != nil {
			panic(err) // let the recovery middleware deal with this
		}
	}
}
