// Code generated by go-swagger; DO NOT EDIT.

package operators

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the generate command

import (
	"net/http"

	"github.com/go-openapi/runtime/middleware"
)

// V2UpdateOperatorPropertiesHandlerFunc turns a function with the right signature into a v2 update operator properties handler
type V2UpdateOperatorPropertiesHandlerFunc func(V2UpdateOperatorPropertiesParams, interface{}) middleware.Responder

// Handle executing the request and returning a response
func (fn V2UpdateOperatorPropertiesHandlerFunc) Handle(params V2UpdateOperatorPropertiesParams, principal interface{}) middleware.Responder {
	return fn(params, principal)
}

// V2UpdateOperatorPropertiesHandler interface for that can handle valid v2 update operator properties params
type V2UpdateOperatorPropertiesHandler interface {
	Handle(V2UpdateOperatorPropertiesParams, interface{}) middleware.Responder
}

// NewV2UpdateOperatorProperties creates a new http.Handler for the v2 update operator properties operation
func NewV2UpdateOperatorProperties(ctx *middleware.Context, handler V2UpdateOperatorPropertiesHandler) *V2UpdateOperatorProperties {
	return &V2UpdateOperatorProperties{Context: ctx, Handler: handler}
}

/*
	V2UpdateOperatorProperties swagger:route PUT /v2/supported-operators/{operator_name} operators v2UpdateOperatorProperties

Updates properties for an operator.
*/
type V2UpdateOperatorProperties struct {
	Context *middleware.Context
	Handler V2UpdateOperatorPropertiesHandler
}

func (o *V2UpdateOperatorProperties) ServeHTTP(rw http.ResponseWriter, r *http.Request) {
	route, rCtx, _ := o.Context.RouteInfo(r)
	if rCtx != nil {
		*r = *rCtx
	}
	var Params = NewV2UpdateOperatorPropertiesParams()
	uprinc, aCtx, err := o.Context.Authorize(r, route)
	if err != nil {
		o.Context.Respond(rw, r, route.Produces, route, err)
		return
	}
	if aCtx != nil {
		*r = *aCtx
	}
	var principal interface{}
	if uprinc != nil {
		principal = uprinc.(interface{}) // this is really a interface{}, I promise
	}

	if err := o.Context.BindValidRequest(r, route, &Params); err != nil { // bind params
		o.Context.Respond(rw, r, route.Produces, route, err)
		return
	}

	res := o.Handler.Handle(Params, principal) // actually handle the request
	o.Context.Respond(rw, r, route.Produces, route, res)

}
