// Code generated by go-swagger; DO NOT EDIT.

package operators

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"net/http"
	"time"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"
	"github.com/go-openapi/strfmt"

	"github.com/openshift/assisted-service/models"
)

// NewV2UpdateOperatorPropertiesParams creates a new V2UpdateOperatorPropertiesParams object,
// with the default timeout for this client.
//
// Default values are not hydrated, since defaults are normally applied by the API server side.
//
// To enforce default values in parameter, use SetDefaults or WithDefaults.
func NewV2UpdateOperatorPropertiesParams() *V2UpdateOperatorPropertiesParams {
	return &V2UpdateOperatorPropertiesParams{
		timeout: cr.DefaultTimeout,
	}
}

// NewV2UpdateOperatorPropertiesParamsWithTimeout creates a new V2UpdateOperatorPropertiesParams object
// with the ability to set a timeout on a request.
func NewV2UpdateOperatorPropertiesParamsWithTimeout(timeout time.Duration) *V2UpdateOperatorPropertiesParams {
	return &V2UpdateOperatorPropertiesParams{
		timeout: timeout,
	}
}

// NewV2UpdateOperatorPropertiesParamsWithContext creates a new V2UpdateOperatorPropertiesParams object
// with the ability to set a context for a request.
func NewV2UpdateOperatorPropertiesParamsWithContext(ctx context.Context) *V2UpdateOperatorPropertiesParams {
	return &V2UpdateOperatorPropertiesParams{
		Context: ctx,
	}
}

// NewV2UpdateOperatorPropertiesParamsWithHTTPClient creates a new V2UpdateOperatorPropertiesParams object
// with the ability to set a custom HTTPClient for a request.
func NewV2UpdateOperatorPropertiesParamsWithHTTPClient(client *http.Client) *V2UpdateOperatorPropertiesParams {
	return &V2UpdateOperatorPropertiesParams{
		HTTPClient: client,
	}
}

/*
V2UpdateOperatorPropertiesParams contains all the parameters to send to the API endpoint

	for the v2 update operator properties operation.

	Typically these are written to a http.Request.
*/
type V2UpdateOperatorPropertiesParams struct {

	/* OperatorName.

	   The operator name.
	*/
	OperatorName string

	/* OperatorProperties.

	   Operator properties to update.
	*/
	OperatorProperties models.OperatorProperties

	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithDefaults hydrates default values in the v2 update operator properties params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *V2UpdateOperatorPropertiesParams) WithDefaults() *V2UpdateOperatorPropertiesParams {
	o.SetDefaults()
	return o
}

// SetDefaults hydrates default values in the v2 update operator properties params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *V2UpdateOperatorPropertiesParams) SetDefaults() {
	// no default values defined for this parameter
}

// WithTimeout adds the timeout to the v2 update operator properties params
func (o *V2UpdateOperatorPropertiesParams) WithTimeout(timeout time.Duration) *V2UpdateOperatorPropertiesParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the v2 update operator properties params
func (o *V2UpdateOperatorPropertiesParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the v2 update operator properties params
func (o *V2UpdateOperatorPropertiesParams) WithContext(ctx context.Context) *V2UpdateOperatorPropertiesParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the v2 update operator properties params
func (o *V2UpdateOperatorPropertiesParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the v2 update operator properties params
func (o *V2UpdateOperatorPropertiesParams) WithHTTPClient(client *http.Client) *V2UpdateOperatorPropertiesParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the v2 update operator properties params
func (o *V2UpdateOperatorPropertiesParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WithOperatorName adds the operatorName to the v2 update operator properties params
func (o *V2UpdateOperatorPropertiesParams) WithOperatorName(operatorName string) *V2UpdateOperatorPropertiesParams {
	o.SetOperatorName(operatorName)
	return o
}

// SetOperatorName adds the operatorName to the v2 update operator properties params
func (o *V2UpdateOperatorPropertiesParams) SetOperatorName(operatorName string) {
	o.OperatorName = operatorName
}

// WithOperatorProperties adds the operatorProperties to the v2 update operator properties params
func (o *V2UpdateOperatorPropertiesParams) WithOperatorProperties(operatorProperties models.OperatorProperties) *V2UpdateOperatorPropertiesParams {
	o.SetOperatorProperties(operatorProperties)
	return o
}

// SetOperatorProperties adds the operatorProperties to the v2 update operator properties params
func (o *V2UpdateOperatorPropertiesParams) SetOperatorProperties(operatorProperties models.OperatorProperties) {
	o.OperatorProperties = operatorProperties
}

// WriteToRequest writes these params to a swagger request
func (o *V2UpdateOperatorPropertiesParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error

	// path param operator_name
	if err := r.SetPathParam("operator_name", o.OperatorName); err != nil {
		return err
	}
	if o.OperatorProperties != nil {
		if err := r.SetBodyParam(o.OperatorProperties); err != nil {
			return err
		}
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
