// Code generated by go-swagger; DO NOT EDIT.

package operators

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"
	"io"

	"github.com/go-openapi/runtime"
	"github.com/go-openapi/strfmt"

	"github.com/openshift/assisted-service/models"
)

// V2UpdateOperatorPropertiesReader is a Reader for the V2UpdateOperatorProperties structure.
type V2UpdateOperatorPropertiesReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *V2UpdateOperatorPropertiesReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {
	case 200:
		result := NewV2UpdateOperatorPropertiesOK()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil
	case 400:
		result := NewV2UpdateOperatorPropertiesBadRequest()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result
	case 401:
		result := NewV2UpdateOperatorPropertiesUnauthorized()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result
	case 403:
		result := NewV2UpdateOperatorPropertiesForbidden()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result
	case 404:
		result := NewV2UpdateOperatorPropertiesNotFound()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result
	case 500:
		result := NewV2UpdateOperatorPropertiesInternalServerError()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result
	default:
		return nil, runtime.NewAPIError("response status code does not match any response statuses defined for this endpoint in the swagger spec", response, response.Code())
	}
}

// NewV2UpdateOperatorPropertiesOK creates a V2UpdateOperatorPropertiesOK with default headers values
func NewV2UpdateOperatorPropertiesOK() *V2UpdateOperatorPropertiesOK {
	return &V2UpdateOperatorPropertiesOK{}
}

/*
V2UpdateOperatorPropertiesOK describes a response with status code 200, with default header values.

Success.
*/
type V2UpdateOperatorPropertiesOK struct {
}

// IsSuccess returns true when this v2 update operator properties o k response has a 2xx status code
func (o *V2UpdateOperatorPropertiesOK) IsSuccess() bool {
	return true
}

// IsRedirect returns true when this v2 update operator properties o k response has a 3xx status code
func (o *V2UpdateOperatorPropertiesOK) IsRedirect() bool {
	return false
}

// IsClientError returns true when this v2 update operator properties o k response has a 4xx status code
func (o *V2UpdateOperatorPropertiesOK) IsClientError() bool {
	return false
}

// IsServerError returns true when this v2 update operator properties o k response has a 5xx status code
func (o *V2UpdateOperatorPropertiesOK) IsServerError() bool {
	return false
}

// IsCode returns true when this v2 update operator properties o k response a status code equal to that given
func (o *V2UpdateOperatorPropertiesOK) IsCode(code int) bool {
	return code == 200
}

func (o *V2UpdateOperatorPropertiesOK) Error() string {
	return fmt.Sprintf("[PUT /v2/supported-operators/{operator_name}][%d] v2UpdateOperatorPropertiesOK ", 200)
}

func (o *V2UpdateOperatorPropertiesOK) String() string {
	return fmt.Sprintf("[PUT /v2/supported-operators/{operator_name}][%d] v2UpdateOperatorPropertiesOK ", 200)
}

func (o *V2UpdateOperatorPropertiesOK) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	return nil
}

// NewV2UpdateOperatorPropertiesBadRequest creates a V2UpdateOperatorPropertiesBadRequest with default headers values
func NewV2UpdateOperatorPropertiesBadRequest() *V2UpdateOperatorPropertiesBadRequest {
	return &V2UpdateOperatorPropertiesBadRequest{}
}

/*
V2UpdateOperatorPropertiesBadRequest describes a response with status code 400, with default header values.

Bad Request.
*/
type V2UpdateOperatorPropertiesBadRequest struct {
	Payload *models.Error
}

// IsSuccess returns true when this v2 update operator properties bad request response has a 2xx status code
func (o *V2UpdateOperatorPropertiesBadRequest) IsSuccess() bool {
	return false
}

// IsRedirect returns true when this v2 update operator properties bad request response has a 3xx status code
func (o *V2UpdateOperatorPropertiesBadRequest) IsRedirect() bool {
	return false
}

// IsClientError returns true when this v2 update operator properties bad request response has a 4xx status code
func (o *V2UpdateOperatorPropertiesBadRequest) IsClientError() bool {
	return true
}

// IsServerError returns true when this v2 update operator properties bad request response has a 5xx status code
func (o *V2UpdateOperatorPropertiesBadRequest) IsServerError() bool {
	return false
}

// IsCode returns true when this v2 update operator properties bad request response a status code equal to that given
func (o *V2UpdateOperatorPropertiesBadRequest) IsCode(code int) bool {
	return code == 400
}

func (o *V2UpdateOperatorPropertiesBadRequest) Error() string {
	return fmt.Sprintf("[PUT /v2/supported-operators/{operator_name}][%d] v2UpdateOperatorPropertiesBadRequest  %+v", 400, o.Payload)
}

func (o *V2UpdateOperatorPropertiesBadRequest) String() string {
	return fmt.Sprintf("[PUT /v2/supported-operators/{operator_name}][%d] v2UpdateOperatorPropertiesBadRequest  %+v", 400, o.Payload)
}

func (o *V2UpdateOperatorPropertiesBadRequest) GetPayload() *models.Error {
	return o.Payload
}

func (o *V2UpdateOperatorPropertiesBadRequest) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.Error)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewV2UpdateOperatorPropertiesUnauthorized creates a V2UpdateOperatorPropertiesUnauthorized with default headers values
func NewV2UpdateOperatorPropertiesUnauthorized() *V2UpdateOperatorPropertiesUnauthorized {
	return &V2UpdateOperatorPropertiesUnauthorized{}
}

/*
V2UpdateOperatorPropertiesUnauthorized describes a response with status code 401, with default header values.

Unauthorized.
*/
type V2UpdateOperatorPropertiesUnauthorized struct {
	Payload *models.InfraError
}

// IsSuccess returns true when this v2 update operator properties unauthorized response has a 2xx status code
func (o *V2UpdateOperatorPropertiesUnauthorized) IsSuccess() bool {
	return false
}

// IsRedirect returns true when this v2 update operator properties unauthorized response has a 3xx status code
func (o *V2UpdateOperatorPropertiesUnauthorized) IsRedirect() bool {
	return false
}

// IsClientError returns true when this v2 update operator properties unauthorized response has a 4xx status code
func (o *V2UpdateOperatorPropertiesUnauthorized) IsClientError() bool {
	return true
}

// IsServerError returns true when this v2 update operator properties unauthorized response has a 5xx status code
func (o *V2UpdateOperatorPropertiesUnauthorized) IsServerError() bool {
	return false
}

// IsCode returns true when this v2 update operator properties unauthorized response a status code equal to that given
func (o *V2UpdateOperatorPropertiesUnauthorized) IsCode(code int) bool {
	return code == 401
}

func (o *V2UpdateOperatorPropertiesUnauthorized) Error() string {
	return fmt.Sprintf("[PUT /v2/supported-operators/{operator_name}][%d] v2UpdateOperatorPropertiesUnauthorized  %+v", 401, o.Payload)
}

func (o *V2UpdateOperatorPropertiesUnauthorized) String() string {
	return fmt.Sprintf("[PUT /v2/supported-operators/{operator_name}][%d] v2UpdateOperatorPropertiesUnauthorized  %+v", 401, o.Payload)
}

func (o *V2UpdateOperatorPropertiesUnauthorized) GetPayload() *models.InfraError {
	return o.Payload
}

func (o *V2UpdateOperatorPropertiesUnauthorized) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.InfraError)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewV2UpdateOperatorPropertiesForbidden creates a V2UpdateOperatorPropertiesForbidden with default headers values
func NewV2UpdateOperatorPropertiesForbidden() *V2UpdateOperatorPropertiesForbidden {
	return &V2UpdateOperatorPropertiesForbidden{}
}

/*
V2UpdateOperatorPropertiesForbidden describes a response with status code 403, with default header values.

Forbidden.
*/
type V2UpdateOperatorPropertiesForbidden struct {
	Payload *models.InfraError
}

// IsSuccess returns true when this v2 update operator properties forbidden response has a 2xx status code
func (o *V2UpdateOperatorPropertiesForbidden) IsSuccess() bool {
	return false
}

// IsRedirect returns true when this v2 update operator properties forbidden response has a 3xx status code
func (o *V2UpdateOperatorPropertiesForbidden) IsRedirect() bool {
	return false
}

// IsClientError returns true when this v2 update operator properties forbidden response has a 4xx status code
func (o *V2UpdateOperatorPropertiesForbidden) IsClientError() bool {
	return true
}

// IsServerError returns true when this v2 update operator properties forbidden response has a 5xx status code
func (o *V2UpdateOperatorPropertiesForbidden) IsServerError() bool {
	return false
}

// IsCode returns true when this v2 update operator properties forbidden response a status code equal to that given
func (o *V2UpdateOperatorPropertiesForbidden) IsCode(code int) bool {
	return code == 403
}

func (o *V2UpdateOperatorPropertiesForbidden) Error() string {
	return fmt.Sprintf("[PUT /v2/supported-operators/{operator_name}][%d] v2UpdateOperatorPropertiesForbidden  %+v", 403, o.Payload)
}

func (o *V2UpdateOperatorPropertiesForbidden) String() string {
	return fmt.Sprintf("[PUT /v2/supported-operators/{operator_name}][%d] v2UpdateOperatorPropertiesForbidden  %+v", 403, o.Payload)
}

func (o *V2UpdateOperatorPropertiesForbidden) GetPayload() *models.InfraError {
	return o.Payload
}

func (o *V2UpdateOperatorPropertiesForbidden) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.InfraError)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewV2UpdateOperatorPropertiesNotFound creates a V2UpdateOperatorPropertiesNotFound with default headers values
func NewV2UpdateOperatorPropertiesNotFound() *V2UpdateOperatorPropertiesNotFound {
	return &V2UpdateOperatorPropertiesNotFound{}
}

/*
V2UpdateOperatorPropertiesNotFound describes a response with status code 404, with default header values.

Error.
*/
type V2UpdateOperatorPropertiesNotFound struct {
	Payload *models.Error
}

// IsSuccess returns true when this v2 update operator properties not found response has a 2xx status code
func (o *V2UpdateOperatorPropertiesNotFound) IsSuccess() bool {
	return false
}

// IsRedirect returns true when this v2 update operator properties not found response has a 3xx status code
func (o *V2UpdateOperatorPropertiesNotFound) IsRedirect() bool {
	return false
}

// IsClientError returns true when this v2 update operator properties not found response has a 4xx status code
func (o *V2UpdateOperatorPropertiesNotFound) IsClientError() bool {
	return true
}

// IsServerError returns true when this v2 update operator properties not found response has a 5xx status code
func (o *V2UpdateOperatorPropertiesNotFound) IsServerError() bool {
	return false
}

// IsCode returns true when this v2 update operator properties not found response a status code equal to that given
func (o *V2UpdateOperatorPropertiesNotFound) IsCode(code int) bool {
	return code == 404
}

func (o *V2UpdateOperatorPropertiesNotFound) Error() string {
	return fmt.Sprintf("[PUT /v2/supported-operators/{operator_name}][%d] v2UpdateOperatorPropertiesNotFound  %+v", 404, o.Payload)
}

func (o *V2UpdateOperatorPropertiesNotFound) String() string {
	return fmt.Sprintf("[PUT /v2/supported-operators/{operator_name}][%d] v2UpdateOperatorPropertiesNotFound  %+v", 404, o.Payload)
}

func (o *V2UpdateOperatorPropertiesNotFound) GetPayload() *models.Error {
	return o.Payload
}

func (o *V2UpdateOperatorPropertiesNotFound) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.Error)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewV2UpdateOperatorPropertiesInternalServerError creates a V2UpdateOperatorPropertiesInternalServerError with default headers values
func NewV2UpdateOperatorPropertiesInternalServerError() *V2UpdateOperatorPropertiesInternalServerError {
	return &V2UpdateOperatorPropertiesInternalServerError{}
}

/*
V2UpdateOperatorPropertiesInternalServerError describes a response with status code 500, with default header values.

Error.
*/
type V2UpdateOperatorPropertiesInternalServerError struct {
	Payload *models.Error
}

// IsSuccess returns true when this v2 update operator properties internal server error response has a 2xx status code
func (o *V2UpdateOperatorPropertiesInternalServerError) IsSuccess() bool {
	return false
}

// IsRedirect returns true when this v2 update operator properties internal server error response has a 3xx status code
func (o *V2UpdateOperatorPropertiesInternalServerError) IsRedirect() bool {
	return false
}

// IsClientError returns true when this v2 update operator properties internal server error response has a 4xx status code
func (o *V2UpdateOperatorPropertiesInternalServerError) IsClientError() bool {
	return false
}

// IsServerError returns true when this v2 update operator properties internal server error response has a 5xx status code
func (o *V2UpdateOperatorPropertiesInternalServerError) IsServerError() bool {
	return true
}

// IsCode returns true when this v2 update operator properties internal server error response a status code equal to that given
func (o *V2UpdateOperatorPropertiesInternalServerError) IsCode(code int) bool {
	return code == 500
}

func (o *V2UpdateOperatorPropertiesInternalServerError) Error() string {
	return fmt.Sprintf("[PUT /v2/supported-operators/{operator_name}][%d] v2UpdateOperatorPropertiesInternalServerError  %+v", 500, o.Payload)
}

func (o *V2UpdateOperatorPropertiesInternalServerError) String() string {
	return fmt.Sprintf("[PUT /v2/supported-operators/{operator_name}][%d] v2UpdateOperatorPropertiesInternalServerError  %+v", 500, o.Payload)
}

func (o *V2UpdateOperatorPropertiesInternalServerError) GetPayload() *models.Error {
	return o.Payload
}

func (o *V2UpdateOperatorPropertiesInternalServerError) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.Error)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}
